"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../components/AppShell";
import { LocalDocument, exportDocument, formatSize, readDocuments } from "../../lib/documents";

export default function DocumentsPage() {
  const [documents, setDocuments] = useState<LocalDocument[]>([]);
  useEffect(() => setDocuments(readDocuments()), []);
  return <AppShell><main className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Workspace</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Documents</h1><p className="mt-2 text-slate-600">Recently uploaded from this browser.</p></div><Link href="/upload" className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Upload document</Link></div>{documents.length === 0 ? <EmptyState /> : <div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4 font-semibold">Document</th><th className="px-6 py-4 font-semibold">Uploaded</th><th className="px-6 py-4 font-semibold">Status</th><th className="px-6 py-4 font-semibold"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-slate-100">{documents.map((document) => <tr key={document.id}><td className="px-6 py-5"><p className="font-semibold text-slate-900">{document.original_filename}</p><p className="mt-1 text-slate-500">{formatSize(document.size_bytes)} · {document.mime_type}</p></td><td className="whitespace-nowrap px-6 py-5 text-slate-600">{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(document.created_at))}</td><td className="px-6 py-5"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold capitalize text-amber-700">{document.processing_status.replaceAll("_", " ")}</span></td><td className="px-6 py-5"><div className="flex items-center justify-end gap-3"><Link href={`/review/${document.id}`} className="font-semibold text-blue-700 hover:text-blue-900">Review</Link><button onClick={() => exportDocument(document)} className="font-semibold text-slate-600 hover:text-slate-950">Export CSV</button></div></td></tr>)}</tbody></table></div></div>}</main></AppShell>;
}
function EmptyState() { return <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="text-lg font-semibold text-slate-900">No documents yet</h2><p className="mt-2 text-slate-600">Upload a document to begin tracking it here.</p><Link href="/upload" className="mt-6 inline-block font-semibold text-blue-700 hover:text-blue-900">Go to upload →</Link></div>; }
