"""Private object storage used for original uploaded documents.

This module deliberately exposes no public URLs.  The filesystem implementation
is suitable for local development; an S3-compatible adapter can implement the
same small protocol without changing the upload API.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path, PurePosixPath
from typing import BinaryIO, Protocol

from app.core.config import get_settings


class StorageError(RuntimeError):
    """Raised when a private object cannot be written or removed."""


class PrivateObjectStorage(Protocol):
    """Minimal interface for private, opaque document objects."""

    def put(self, key: str, source: BinaryIO) -> None:
        """Persist ``source`` under an opaque key, without making it public."""

    def open(self, key: str) -> BinaryIO:
        """Open a private object for reading.  The caller closes the stream."""

    def delete(self, key: str) -> None:
        """Remove a previously persisted object if it exists."""


class FilesystemPrivateStorage:
    """Atomic local private storage rooted outside the application's static files."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).expanduser().resolve()

    def put(self, key: str, source: BinaryIO) -> None:
        target = self._path_for(key)
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        os.chmod(self.root, 0o700)
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            os.chmod(target.parent, 0o700)
            with tempfile.NamedTemporaryFile(
                mode="wb", dir=target.parent, prefix=".upload-", delete=False
            ) as temporary:
                temporary_name = temporary.name
                shutil.copyfileobj(source, temporary)
                temporary.flush()
                os.fsync(temporary.fileno())
            os.chmod(temporary_name, 0o600)
            # Keys are generated by the service, so a collision is an error.
            # Linking avoids overwriting an existing object if one ever occurs.
            os.link(temporary_name, target)
            os.unlink(temporary_name)
        except FileExistsError as error:
            if "temporary_name" in locals() and os.path.exists(temporary_name):
                os.unlink(temporary_name)
            raise StorageError("storage key already exists") from error
        except OSError as error:
            if "temporary_name" in locals() and os.path.exists(temporary_name):
                os.unlink(temporary_name)
            raise StorageError("could not persist private document") from error

    def delete(self, key: str) -> None:
        try:
            self._path_for(key).unlink(missing_ok=True)
        except OSError as error:
            raise StorageError("could not remove private document") from error

    def open(self, key: str) -> BinaryIO:
        """Open an object without exposing its filesystem path to callers."""
        try:
            return self._path_for(key).open("rb")
        except FileNotFoundError as error:
            raise StorageError("private object does not exist") from error
        except OSError as error:
            raise StorageError("could not read private document") from error

    def _path_for(self, key: str) -> Path:
        path = PurePosixPath(key)
        if not key or path.is_absolute() or ".." in path.parts:
            raise StorageError("invalid private storage key")
        resolved = (self.root / Path(*path.parts)).resolve()
        try:
            resolved.relative_to(self.root)
        except ValueError as error:
            raise StorageError("invalid private storage key") from error
        return resolved


def get_private_storage() -> PrivateObjectStorage:
    """Return the configured private-storage implementation."""
    return FilesystemPrivateStorage(get_settings().private_storage_path)
